name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.12.1
        
      - name: Github Checkout
        uses: actions/checkout@v4

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.10.5

      - name: 📦 Build
        run: npm run build
            
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.13.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
